export const DANGEROUS_PATTERNS: RegExp[] = [
    /rm\s+(-rf?|--recursive)\s+[/~]/i,
    /rm\s+-rf?\s+\*/i,
    /rmdir\s+[/~]/i,
    /dd\s+if=/i,
    /mkfs/i,
    /fdisk/i,
    /parted/i,
    /shutdown/i,
    /reboot/i,
    /halt/i,
    /poweroff/i,
    /init\s+[06]/i,
    /chmod\s+(-R\s+)?777\s+[/~]/i,
    /chown\s+-R\s+.*\s+[/~]/i,
    /nc\s+-l/i,
    /netcat\s+-l/i,
    /curl\s+.*\|\s*(bash|sh)/i,
    /wget\s+.*\|\s*(bash|sh)/i,
    /:\(\)\s*\{\s*:\|:&\s*\}\s*;/,
];

/** Read-only commands that can be auto-approved without asking. */
export const SAFE_PATTERNS: RegExp[] = [
    /^(ls|dir|pwd|cd|echo|cat|head|tail|less|more|wc)(\s|$)/i,
    /^(find|locate|which|whereis|file|stat)(\s|$)/i,
    /^git\s+(status|log|diff|show|branch|remote|tag)(\s|$)/i,
    /^(npm|yarn|pnpm|bun)\s+(list|ls|outdated)(\s|$)/i,
    /^pip\s+(list|show|freeze)(\s|$)/i,
    /^cargo\s+(tree|search)(\s|$)/i,
    /^(grep|rg|awk|sed|cut|sort|uniq|tr|diff|comm)(\s|$)/i,
    /^(date|cal|uptime|whoami|id|groups|hostname|uname)(\s|$)/i,
    /^(env|printenv|set)$/i,
    /^(ps|top|htop|pgrep)(\s|$)/i,
];
